<Project>
  <PropertyGroup>
    <!-- Common properties for all projects -->
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>

    <!-- Repository information -->
    <RepositoryUrl>https://github.com/gragra33/Blazing.Mvvm</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <Copyright>Copyright © Graeme Grant</Copyright>
    <Authors>Graeme Grant (@gragra33); Mishael Ogochukwu (@mishael-o)</Authors>

    <!-- Package defaults -->
    <PackageProjectUrl>https://github.com/gragra33/Blazing.Mvvm</PackageProjectUrl>
    <PackageReleaseNotes>https://github.com/gragra33/Blazing.Mvvm/releases</PackageReleaseNotes>

    <!-- Source link + symbols -->
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="All" />
    <PackageReference Include="Nerdbank.GitVersioning" PrivateAssets="All" />
  </ItemGroup>

  <Target Name="OverridePrereleasePackageVersion"
          AfterTargets="GetBuildVersion"
          Condition="'$(PublicRelease)' == 'False'">
    <PropertyGroup>
      <PackageVersion>$(BuildVersionSimple)-beta</PackageVersion>
    </PropertyGroup>
  </Target>
</Project>
